name: linter
on:
  push:
    branches: [feature/gitActions]
  pull_request:
    branches: [feature/gitActions]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      # Désactive tout les language par défault
      VALIDATE_ALL_CODEBASE: false

      #Active uniquement le javascript (ESLint
      VALIDATE_JAVASCRIPT_ESLINT: true

      # Test qu'un fichier spécifique
      FILTER_REGEX_INCLUDE: .test.js


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v5

