#Ne prend en considération que si le fichier a été modifié durant le dernier push
#Si non il le valide comme étant correct malgrès les erreurs

name: linter
on:
  push:
    branches: [feature/gitActions]
  pull_request:
    branches: [feature/gitActions]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          #récupère tout l'historique pour permettre la comparaison des fichiers
          fetch-depth: 0
          #Force la récupération sur une branche spécifique
          ref: feature/gitActions

      - name: Super-Linter
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          DEFAULT_BRANCH: feature/gitActions

          # Désactive tout les language par défault
          VALIDATE_ALL_CODEBASE: false
          #Active uniquement le javascript (ESLint
          VALIDATE_JAVASCRIPT_ESLINT: true
          # Test qu'un fichier spécifique
          FILTER_REGEX_INCLUDE: .*test\.js