name: linter
on:
  push:
    branches: [feature/gitActions]
  pull_request:
    branches: [feature/gitActions]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v5

